console.log("hello");
console.log("안녕하세요");
var n=10;
console.log("결과는 %d입니다",n);
console.log("결과는"+n+"입니다");
var msg="happy day!!";
console.log("메세지 %s!!!",msg);
console.log("메세지" + msg+"!!!");
var j={irum:"홍길동"};
console.log("json 출력 : %j",j);